### ISSUE TITLE
Node 10 build fails a lot in a flakey way

### ISSUE THREAD

**Issue by SCdF** [medic/medic-couch2pg#42]
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-101-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/app/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/usr/app/node_modules/node-libcurl/lib/binding" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
```

Node 8 doesn't seem to have this issue, and restarting the Node 10 build often makes this compilation step pass.

**Comment by latin-panda** [comment]
I experienced similar error with Node 8 and Node 12, but working in Node 10. Maybe id' be good to check the dependencies in package json if this keeps happening.
